# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: tilde
    - DOXYFILE: $TRAVIS_BUILD_DIR/DOXYGEN
    - GH_REPO_REF: github.com/njazz/tilde.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - qt5-default 
      - qttools5-dev-tools



# Generate and deploy documentation #after_success
script:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocs.sh
  - ./generateDocs.sh
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake ..
  - make
